### ISSUE TITLE
Customizing Theme Colors

### ISSUE THREAD

**Issue by Asduveneck** [IonicaBizau/github-calendar#96] opened 2020-02-07 02:32 UTC
Is it possible to color the colors for each contribution square? I tried modifying `t.exports` (line 164) but that didn't work. I also updated where we grab the  [original code](https://github.com/Asduveneck/personal_site/blob/change_colors/assets/js/github_calendar_code.js) to return a new `fill` value (line 175...), but that didn't work.

**Comment by IonicaBizau** [comment] 2020-03-24 23:27
Duplicate of #91

**Closed as completed by IonicaBizau** 2020-03-24 23:27 UTC
