### ISSUE TITLE
Responsive Function isn't working

### ISSUE THREAD

**Issue by wit03** [IonicaBizau/github-calendar#61] opened 2018-08-24 07:38 UTC
I've tried 
`GitHubCalendar(".calendar", "wit03", {
    responsive: true
});`
it still doesn't work

**Comment by iphysresearch** [comment] 2018-08-24 16:18
I think you need use the new `github-calendar.min.js`.

You can check the source code of https://ionicabizau.github.io/github-calendar/example/   ....

**Comment by IonicaBizau** [comment] 2019-01-21 16:55
Duplicate of #51

**Closed as completed** 2019-01-21 17:06 UTC
Labels: bug, duplicate
