### ISSUE TITLE
Hide the main chart on small screens

### ISSUE THREAD

**Issue by eternal-flame-AD** [IonicaBizau/github-calendar#69] opened 2018-12-10 03:38 UTC
I found that the main chart would overflow on small screens so maybe we should hide it on small screens. It takes at least a standard middle screen to fit the whole svg.
![image](https://user-images.githubusercontent.com/35571479/49709458-74720900-fc6f-11e8-8ea6-56e8e39b5165.png)

An example of the changes I intended:
https://gitlab.com/eternal-flame-AD/eternalflame-cn/blob/cdfc652764b37658d52d427c8413fe48dbe0e2d5/layouts/shortcodes/github-calendar.html#L12-16

**Comment by IonicaBizau** [comment] 2019-01-21 16:26
Duplicate of #51

**Closed as completed** 2019-01-21 17:06 UTC
Labels: bug, duplicate
