### ISSUE TITLE
CORS is preventing the request

### ISSUE THREAD

**Issue by vvzen** [IonicaBizau/github-calendar#54] opened 2018-06-13 15:18 UTC
The script was running fine until today.

```Failed to load resource: Origin http://mywebsite.com is not allowed by Access-Control-Allow-Origin.```

Tested under Safari and Firefox.

![github-loader-error](https://user-images.githubusercontent.com/10340139/41360746-c5d3248e-6f2d-11e8-98c8-0dd14a9f372a.png)

**Comment by IonicaBizau** [comment] 2018-06-13 15:23
@izuzak Can you please take a look at this?

@vvzen In the meantime, you can setup a different proxy, following the docs. Urlreq is just the default one.

**Comment by izuzak** [comment] 2018-06-13 15:32
> @izuzak Can you please take a look at this?

@IonicaBizau Happy to take a look when I find a moment. Can you please open an issue with clear steps to reproduce? 🙏

**Comment by IonicaBizau** [comment] 2018-06-13 15:35
Well, actually it's because _Over Quota_ 🙈 

> Over Quota
> This application is temporarily over its serving quota. Please try again later.

And because that response doesn't have the CORS headers, the error appears in the browser.
To reproduce, open: https://urlreq.appspot.com/req?method=GET&url=https://github.com/IonicaBizau

**Comment by izuzak** [comment] 2018-06-13 15:37
> And because that response doesn't have the CORS headers, the error appears in the browser.
> To reproduce, open: https://urlreq.appspot.com/req?method=GET&url=https://github.com/IonicaBizau

Problem solved, then 😄 You can spin up your own instance of that server (the code is open source) and buy additional quota for yourself.

**Comment by IonicaBizau** [comment] 2018-06-13 16:04
Indeed :sweat_smile:

**Comment by IonicaBizau** [comment] 2019-01-21 17:07
Going to close this for now. The solution is to use a custom proxy if you don't want to depend on the default proxy.

**Closed as completed by IonicaBizau** 2019-01-21 17:07 UTC

**Comment by ghjansen** [comment] 2019-08-19 13:40
This issue is happening again.
> Going to close this for now. The solution is to use a custom proxy if you don't want to depend on the default proxy.

@IonicaBizau any directions on how to do that? 
There are free alternative proxies that can be used?
This issue is a big downside when using your project.

**Comment by nunoskew** [comment] 2019-08-22 22:38
Hi IonicaBizau, great tool!

However I'm getting the same problem and apparently the project's page too: https://ionicabizau.github.io/github-calendar/example/

Is there any fix?

Thanks!

**Comment by ghjansen** [comment] 2019-08-23 01:39
To whom it might concern, @Cipher-Coder did a great step-by-step on how to get [izuzak/urlreq](https://github.com/izuzak/urlreq) running through Google Cloud. See it in full at izuzak/urlreq#6.

Despite the moderate complexity of this workaround, it seems that a better solution is still much needed. Thoughts?

**Comment by IonicaBizau** [comment] 2019-08-26 09:05
I remember I saw a pretty nice proxy service, but I don't remember its name and since I really enjoyed using @izuzak's tool, I just decided to use it.

The library accepts the `proxy` option:

```js
GitHubCalendar(".calendar", "your-username", {
  responsive: true,
  proxy: function (url) {
      return "https://the-proxy-domain.com/req?method=GET&url=" + url;
   }
});
```

The url returned by the `proxy` function can be any endpoint from your server side of your app (e.g. a php file or Express endpoint etc).

**Comment by Funkh0user** [comment] 2020-04-05 02:18
I am having the problem described in this thread,. I'm using the githubcontrutions package in my react app portfolio page. everything worked fine for a long time till today, when I started getting the same qouta and cors errors. I don't understand what was mentioned previously in this thread about purchasing more qouta....what exactly do I need to do to get this module up and running again? I've never used any kind of proxy except for https://cors-anywhere.herokuapp.com/ .....not exactly certain how hard it is or if its worth the bother....

**Comment by Funkh0user** [comment] 2020-04-05 04:29
I'm having the qouta problems described in this thread but i'm uncertain how to implement the solutions talked about. could someone explain to me in more detail what the exact workaround for this is? When I tried use the proxy method above, It didn't solve my problems.

**Comment by hayorov** [comment] 2020-04-05 06:34
I'm also confirming that urlreq.appspot.com is under "Over Quota". https://github.com/izuzak/urlreq/issues/7

**Comment by Funkh0user** [comment] 2020-04-10 07:34
its back up again. I'd still love a more detailed explanation on how to use a custom proxy or to acquire more qouta.

**Comment by IonicaBizau** [comment] 2020-04-10 17:21
In the latest releases I implemented the new proxy from @Bloggify. Currently there are no max quotas, but using the default cache is recommended.
