### ISSUE TITLE
The example shows only black boxes

### ISSUE THREAD

**Issue by vgvassilev** [IonicaBizau/github-calendar#122] opened 2020-11-01 13:11 UTC
I have the same issue that can be seen in the example: https://bloggify.github.io/github-calendar/example

How we can fix this?

**Comment by shijiezhou1** [comment] 2020-11-01 13:33
I think this repo is no longer maintains by this guy. We need to find something else.

**Comment by moselhy** [comment] 2020-11-01 14:10
#120

**Comment by IonicaBizau** [comment] 2020-11-01 17:01
Duplicate of #120. Contributions are welcome to fix this.

**Closed as completed by IonicaBizau** 2020-11-01 17:01 UTC
