### ISSUE TITLE
Appspot quota

### ISSUE THREAD

**Issue by kaangokdemir** [IonicaBizau/github-calendar#79] opened 2019-08-22 22:36 UTC
It looks like this script growth very fast. Couldn't bare with 1GB AppSpot quote per day. It works most of hours in a day still.

**Comment by nunoskew** [comment] 2019-08-22 23:09
Hi IonicaBizau, great tool!

However I'm getting the same problem and apparently the project's page too: https://ionicabizau.github.io/github-calendar/example/

Is there any (free) fix?

Thanks!

**Comment by ghjansen** [comment] 2019-08-23 15:21
@kaangokdemir @nunoskew 

I suggest you to take a look at #54 and izuzak/urlreq#6
I hope it helps.

**Comment by IonicaBizau** [comment] 2020-01-16 17:20
Duplicate of #54.

**Closed as completed by IonicaBizau** 2020-01-16 17:20 UTC
Labels: duplicate
